version: "3"

services:
  system-monitor:
    build: ./system_monitor
    container_name: system-monitor
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: "super-secret-key"
      DJANGO_DEBUG: "False"

  report-service:
    build: ./report_service
    container_name: report-service
    ports:
      - "8001:8000"
    depends_on:
      - system-monitor
    environment:
      DJANGO_SECRET_KEY: "super-secret-key"
      DJANGO_DEBUG: "False"
      SYSTEM_MONITOR_URL: "http://system-monitor:8000/api/stats/"

  auth-service:
    build: ./auth_service
    container_name: auth-service
    ports:
      - "8002:8000"
    depends_on:
      - report-service
      - system-monitor
    environment:
      DJANGO_SECRET_KEY: "super-secret-key"
      DJANGO_DEBUG: "False"
      SYSTEM_MONITOR_URL: "http://system-monitor:8000/api/stats/"
      REPORT_SERVICE_URL: "http://report-service:8001/api/history/"
