version: "3"

services:
  system-monitor:
    build: ./system_monitor
    container_name: system-monitor
    ports:
      - "8000:8000"
    volumes:
      - ./system_monitor:/app
    restart: always

  report-service:
    build: ./report_service
    container_name: report-service
    ports:
      - "8001:8000"
    volumes:
      - ./report_service:/app
    depends_on:
      - system-monitor
    restart: always

  auth-service:
    build: ./auth_service
    container_name: auth-service
    ports:
      - "8002:8000"
    volumes:
      - ./auth_service:/app
    restart: always
