services:
  - type: web
    name: system-monitor
    env: docker
    plan: free
    dockerfilePath: ./system_monitor/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-system-monitor-secret-key
      - key: DJANGO_DEBUG
        value: False

  - type: web
    name: report-service
    env: docker
    plan: free
    dockerfilePath: ./report_service/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-report-service-secret-key
      - key: DJANGO_DEBUG
        value: False
      - key: SYSTEM_MONITOR_URL
        value: https://system-monitor.onrender.com/api/stats/

  - type: web
    name: auth-service
    env: docker
    plan: free
    dockerfilePath: ./auth_service/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-auth-service-secret-key
      - key: DJANGO_DEBUG
        value: False
      - key: SYSTEM_MONITOR_URL
        value: https://system-monitor.onrender.com/api/stats/
      - key: REPORT_SERVICE_URL
        value: https://report-service.onrender.com/api/history/
